inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puma/daemon/dsl.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/puma-daemon.rb'

# Gemspec/DevelopmentDependencies:
#   Enabled: false
