#!/usr/bin/env ruby
# frozen_string_literal: true

require 'puma/daemon'

# If we are passing -d or --daemonize, do so
# otherwise invoke to the original puma
if (ARGV & %w[-d --daemonize]).size.positive?
  ARGV.delete '-d'
  ARGV.delete '--daemonize'
end

Puma::Daemon::CLI.new(ARGV)&.run
